"""add employee relationship

Revision ID: 632cdd4bd907
Revises: bfe1dbe2e73e
Create Date: 2026-04-23 14:54:42.104507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '632cdd4bd907'
down_revision: Union[str, Sequence[str], None] = 'bfe1dbe2e73e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('shop_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'user', 'shop', ['shop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'shop_id')
    # ### end Alembic commands ###
