"""add payment method to order

Revision ID: e964a9362b70
Revises: b354846c2a04
Create Date: 2026-04-24 22:31:07.458319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e964a9362b70'
down_revision: Union[str, Sequence[str], None] = 'b354846c2a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create the enum type first
    payment_method_enum = sa.Enum('STRIPE', 'COD', name='paymentmethod')
    payment_method_enum.create(op.get_bind())
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('payment_method', payment_method_enum, nullable=False, server_default='STRIPE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'payment_method')
    # ### end Alembic commands ###
    sa.Enum(name='paymentmethod').drop(op.get_bind())
